### ISSUE TITLE
Transform User_Adapter in a doctrine entity. 

### ISSUE THREAD

**Issue by nlegoff** [alchemy-fr/Phraseanet#573]
# Task list to move user management from self to doctrine

Every point is related to a single PR with a single commit
1. [x] Create the `User` entity and User Repository + patch.
2. [x] Add `UserQuery` entity, move `saveQuery()` logic to use the new entity with a One-To-Many relationship + patch.
3. [x] Add `UserSetting` entity, move all user preferences stuff in `User_Adapter` to use the new entuty with a One-To-Many relationship + patch (do not migrate notifications settings).
4. [x] Add default `UserSettings` to `User` entity.
5. [x] Add `UserNotificationSetting` setting, use One-To-Many relationship + patch.
6. [x] The property `model_of` takes the form of a One-To-One, Self-referencing relationship as a template is also a user entity.
7. [x]  `ACL` property is not removed from User entity. It is set as an unmapped property. ACL object needs an `Alchemy\Phrasea\Application` to be instantiated. So the ACL() methods take the `Application` object as argument and becomes ACL($app). `$user->ACL($app)->getRights();`
8. [x] The functions `is_template()`, `is_special()`, `get_display_name()` must be reported to the user entity as helpers.
9. [x] Move `get_protected_rss_url()` method to the random object.
10. [x] Remove `get_usr_id_from_login()` method and use a repository method instead.
11. [x] Remove `get_usr_id_from_email()` method and use a repository method instead.
12. [x] Remove `get_wrong_email_users()` method and use a repository method instead.
13. [x] Remove `get_sys_admins()` method and use a repository method instead.
14. [x] The code inside `set_sys_admins()` function should me moved to the appropriate controller.
15. [x] The function `updateClientInfos()` must be moved to the `Session_Logger` object.
16. [x] The logic inside the `set_geonameid(`) function must be moved to a Doctrine event listener. On `preUpdate` event it would fill the proper country code **only** if the geonameid changed.
17. [x] The logic inside the `set_template()` function must be moved to a Doctrine event listener. On `preUpdate` event it would reset the user informations, settings, notifications settings and ftp credentials.
18. [x] The logic inside the `delete()` function must be moved to a doctrine event listener. On `postRemove` event it will remove all users relative stuff. Remove only toggles a boolean value
19. [x] 
    - Remove singleton stuff, user must now be loaded using user repository to load non authenticated users.
    - Move all sql queries concerning user table to the user repository.
    - Replace old getter and setter by new ones, calls to old query by the repository methods.
    - Delete `User_Adapter` class.
    - Create all relation from previous created entities that involves user.
20. [ ] ~~Set cache mechanism. `$userRepository->find($userId);` method will now be called instead of old `User_Adapter::getInstance($usrId);`and we must keep a cache mechanism for this as it is called in many places. The problem is we can cache only some custom queries (useResultCache(true) on Query object) with Doctrine. [This](http://stackoverflow.com/a/15702644) can be easily solve for user entity and keep similar cache mechanism as the previous implementation.~~
